DROP TABLE `log`;

create table log (
id bigint generated by default as identity, 
captain_name varchar(255), 
cargo integer not null, 
origin varchar(255), 
ship_class varchar(255), 
ship_name varchar(255), 
primary key (id)
);